name: Deploy to Cloud Run

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  PROJECT_ID: loganszeto-health-sync
  REGION: us-west2
  SERVICE_NAME: loganszeto
  REGISTRY: us-west2-docker.pkg.dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      
      - name: Install dependencies
        run: npm install
      
      - name: Build with Next.js
        run: |
          touch .env.local
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env.local
          cp next.config.server.mjs next.config.mjs
          export MONGODB_URI="${{ secrets.MONGODB_URI }}"
          npm run build:server
      
      - name: Google Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Configure Docker
        run: |
          gcloud auth configure-docker ${{ env.REGISTRY }}
      
      - name: Build and Push Container
        run: |
          docker build \
            --build-arg MONGODB_URI="${{ secrets.MONGODB_URI }}" \
            -t ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/cloud-run-source-deploy/${{ env.SERVICE_NAME }}:${{ github.sha }} .
          docker push ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/cloud-run-source-deploy/${{ env.SERVICE_NAME }}:${{ github.sha }}
      
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/cloud-run-source-deploy/${{ env.SERVICE_NAME }}:${{ github.sha }}
          flags: |
            --timeout=300
            --cpu=1
            --memory=512Mi
            --concurrency=80
          env_vars: |
            MONGODB_URI=${{ secrets.MONGODB_URI }} 